### ISSUE TITLE
Unable to install v1.0.4

### ISSUE THREAD

**Issue by sharmasharad795** [zafercavdar/fasttext-langdetect#10]
Hi,

I've been trying to install using pip3 and keep running into this error : FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

Could you please help out?
Regards,
Sharad

**Comment by chschroeder** [comment]
Can confirm, same here.

**Comment by zafercavdar** [comment]
Installation issues are solved in 1.0.5

**Comment by zafercavdar** [comment]
It seems that the requirements.txt file is not included in the dist folder while building setup.py and setup.py depends on requirements. I hard-coded req list to setup.py and released a new version.
