### ISSUE TITLE
Unable to install version 1.0.4

### ISSUE THREAD

**Issue by dheepakg** [zafercavdar/fasttext-langdetect#9]
Command used: `pip install fasttext-langdetect==1.0.4`

Error Message:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting fasttext-langdetect==1.0.4
  Using cached fasttext-langdetect-1.0.4.tar.gz (6.8 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/b1/b1/8fa4bc80f4d33be39f017b7e9096ed846748bbc360e6d53b68c0286b6763/fasttext-langdetect-1.0.4.tar.gz#sha256=ace3ae85002098fe7cc14cb9db48c3f6b93209cc968e4028907865bd9527c618 (from https://pypi.org/simple/fasttext-langdetect/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement fasttext-langdetect==1.0.4 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4)
ERROR: No matching distribution found for fasttext-langdetect==1.0.4

**Comment by zafercavdar** [comment]
Installation issues are solved in 1.0.5
